import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-screen bg-gray-900 h-screen flex flex-wrap justify-center items-center'>
        <p className='text-sky-500 text-3xl font-bold'>Hello Zaxe!</p>
      </div>
    </>
  );
}
